CMakeLists.txt: fix systemd service file installation and drop upstart file
:Release Notes:
With multilib it installs the service file in wrong location causing:
ERROR: com.webos.service.flowmanager-1.0.0-5-r1 do_package: SYSTEMD_SERVICE_com.webos.service.flowmanager value flowmgr.service does not exist
ERROR: com.webos.service.flowmanager-1.0.0-5-r1 do_package: Function failed: systemd_populate_packages
ERROR: Logfile of failure stored in: com.webos.service.flowmanager/1.0.0-5-r1/temp/log.do_package.40884
ERROR: Task (meta-webos/recipes-webos/com.webos.service.flowmanager/com.webos.service.flowmanager.bb:do_package) failed with exit code '1'

:Detailed Notes:
The file is in:
com.webos.service.flowmanager/1.0.0-5-r1/image/lib64/systemd/system/flowmgr.service
use sysconfdir like all other recipes do.

:Testing Performed:

:QA Notes:

:Issues Addressed:

Change-Id: I8e96b18eb2a30d6bb2d2cf635badd6220ff5729d
Reviewed-on: http://gpro.lge.com/250943
Reviewed-by: OSE Helper Bot <ose@ci.lgsvl.net>
Reviewed-by: Martin Jansa <martin.jansa@lge.com>
Tested-by: Martin Jansa <martin.jansa@lge.com>